/// used to select the top first ranked values 
table Items
	lineageTag: 94074740-310c-44d1-a718-7bb459507bd0

	measure 'Parameter Value' = SELECTEDVALUE('Items'[Parameter], 10)
		formatString: 0
		lineageTag: 031bf870-b03f-4b1e-b62b-b51e784f0236

	column Parameter
		dataType: int64
		formatString: 0
		lineageTag: be91de31-6cc8-409d-bd08-4e0be8e59557
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Items = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1)

	annotation PBI_Id = bf9b4c3a7c1e4c0fb9c8a074ea39cece

